services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=saas
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - saas-network

  db:
    image: mysql:8.0
    container_name: saas-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=saas
      - MYSQL_USER=saas
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - saas-network

  redis:
    image: redis:7-alpine
    container_name: saas-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - saas-network

volumes:
  mysql_data:
  redis_data:

networks:
  saas-network:
    driver: bridge